DEBUG 2016-05-23 18:48:53,683: 	 Executing command: 'submit'
DEBUG 2016-05-23 18:48:53,691: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2016-05-23 18:49:05,799: 	 Executing command: 'submit'
DEBUG 2016-05-23 18:49:05,799: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2016-05-23 18:49:05,838: 	 Checking credentials
DEBUG 2016-05-23 18:49:05,838: 	 Found proxy file /tmp/x509up_u46497
DEBUG 2016-05-23 18:49:05,838: 	 Getting proxy life time left
DEBUG 2016-05-23 18:49:06,041: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -timeleft
 output : 677899

 error: 
 retcode : 0
DEBUG 2016-05-23 18:49:06,145: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -actimeleft
 output : 677898

 error: 
 retcode : 0
DEBUG 2016-05-23 18:49:06,145: 	 Proxy valid for 188:18:19 hours
INFO 2016-05-23 18:49:06,145: 	 Will use CRAB configuration file crab3_MC.py
DEBUG 2016-05-23 18:49:06,145: 	 Loading CRAB configuration file.
ERROR 2016-05-23 18:49:06,977: 	 Error while loading CRAB configuration:
'Configuration' object has no attribute 'Data'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-05-23 18:49:06,977: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 295, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'Configuration' object has no attribute 'Data'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-05-23 18:54:56,945: 	 Executing command: 'submit'
DEBUG 2016-05-23 18:54:56,946: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2016-05-23 18:54:56,957: 	 Checking credentials
DEBUG 2016-05-23 18:54:56,957: 	 Found proxy file /tmp/x509up_u46497
DEBUG 2016-05-23 18:54:56,958: 	 Getting proxy life time left
DEBUG 2016-05-23 18:54:57,060: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -timeleft
 output : 677547

 error: 
 retcode : 0
DEBUG 2016-05-23 18:54:57,164: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -actimeleft
 output : 677547

 error: 
 retcode : 0
DEBUG 2016-05-23 18:54:57,164: 	 Proxy valid for 188:12:27 hours
INFO 2016-05-23 18:54:57,165: 	 Will use CRAB configuration file crab3_MC.py
DEBUG 2016-05-23 18:54:57,165: 	 Loading CRAB configuration file.
ERROR 2016-05-23 18:54:58,394: 	 Error while loading CRAB configuration:
'Configuration' object has no attribute 'Data'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-05-23 18:54:58,394: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 295, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'Configuration' object has no attribute 'Data'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-05-23 19:34:20,621: 	 Executing command: 'submit'
DEBUG 2016-05-23 19:34:20,622: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2016-05-23 19:34:20,634: 	 Checking credentials
DEBUG 2016-05-23 19:34:20,634: 	 Found proxy file /tmp/x509up_u46497
DEBUG 2016-05-23 19:34:20,634: 	 Getting proxy life time left
DEBUG 2016-05-23 19:34:20,737: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -timeleft
 output : 675184

 error: 
 retcode : 0
DEBUG 2016-05-23 19:34:20,840: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -actimeleft
 output : 675184

 error: 
 retcode : 0
DEBUG 2016-05-23 19:34:20,840: 	 Proxy valid for 187:33:04 hours
INFO 2016-05-23 19:34:20,841: 	 Will use CRAB configuration file crab3_MC.py
DEBUG 2016-05-23 19:34:20,841: 	 Loading CRAB configuration file.
DEBUG 2016-05-23 19:34:21,157: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2016-05-23 19:34:21,158: 	 Working area '/uscms_data/d3/sdurgut/SL6/CMSSW_5_3_32/src/Analysis/FourMuonPAT/test/GEN-SIM/crab_H02UpsMuMu_ArtifactTest' already exists 
Please change the requestName in the config file
ERROR 2016-05-23 19:34:21,158: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 299, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1605/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/sdurgut/SL6/CMSSW_5_3_32/src/Analysis/FourMuonPAT/test/GEN-SIM/crab_H02UpsMuMu_ArtifactTest' already exists 
Please change the requestName in the config file
DEBUG 2016-11-26 13:44:02,735: 	 Executing command: 'submit'
DEBUG 2016-11-26 13:44:02,736: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2016-11-26 13:44:02,747: 	 Checking credentials
DEBUG 2016-11-26 13:44:02,748: 	 Proxy file /tmp/x509up_u46497 not found
DEBUG 2016-11-26 13:44:02,748: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-11-26 13:44:10,464: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2016-11-26 13:44:10,566: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -timeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-11-26 13:44:10,669: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u46497 -actimeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-11-26 13:44:10,772: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u46497 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2016-11-26 13:44:10,772: 	 Proxy created.
INFO 2016-11-26 13:44:10,772: 	 Will use CRAB configuration file crab3_MC.py
DEBUG 2016-11-26 13:44:10,773: 	 Loading CRAB configuration file.
DEBUG 2016-11-26 13:44:10,788: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2016-11-26 13:44:10,788: 	 Working area '/uscms_data/d3/sdurgut/SL6/CMSSW_5_3_32/src/Analysis/FourMuonPAT/test/GEN-SIM/crab_H02UpsMuMu_ArtifactTest' already exists 
Please change the requestName in the config file
ERROR 2016-11-26 13:44:10,788: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/sdurgut/SL6/CMSSW_5_3_32/src/Analysis/FourMuonPAT/test/GEN-SIM/crab_H02UpsMuMu_ArtifactTest' already exists 
Please change the requestName in the config file
DEBUG 2017-06-09 16:37:25,525: 	 Executing command: 'kill'
DEBUG 2017-06-09 16:37:25,526: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
ERROR 2017-06-09 16:37:25,527: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2017-06-09 16:37:25,527: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 562, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
DEBUG 2017-06-09 16:37:33,698: 	 Executing command: 'kill'
DEBUG 2017-06-09 16:37:33,698: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
DEBUG 2017-06-09 16:37:37,814: 	 Executing command: 'kill'
DEBUG 2017-06-09 16:37:37,814: 	 Found CRAB cache file /uscms/home/sdurgut/.crab3
ERROR 2017-06-09 16:37:37,815: 	 Error: all is not a valid CRAB project directory.
ERROR 2017-06-09 16:37:37,815: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch6/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: all is not a valid CRAB project directory.
